//! Generated gateway bootstrap for sdkwork-promotion.
//! Regenerated by pnpm gateway:assembly:materialize when bootstrap contains todo!().

use axum::Router;
use sdkwork_promotion_service_host::PromotionServiceHost;
use std::sync::Arc;

pub struct ApiAssembly {
    pub router: Router,
}

pub async fn assemble_api_router(host: Arc<PromotionServiceHost>) -> ApiAssembly {
    let mut router = Router::new();
    router =
        router.merge(sdkwork_routes_promotion_app_api::gateway_mount_business(host.clone()).await);
    router = router.merge(sdkwork_routes_promotion_backend_api::gateway_mount_business(host).await);
    ApiAssembly { router }
}

pub async fn assemble_backend_business_router(
    host: Arc<PromotionServiceHost>,
) -> ApiAssembly {
    ApiAssembly {
        router: sdkwork_routes_promotion_backend_api::gateway_mount_business(host).await,
    }
}
