-- SDKWork promotion consolidated initialization baseline (sqlite)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/sqlite/0001_promotion_baseline.sql
-- sdkwork:migration
-- id: 0001_promotion_core
-- engine: sqlite
-- module: promotion
-- purpose: L2 promotion offer, coupon stock, code, user coupon, ledger, discount application
-- reversible: true
-- transactional: true

CREATE TABLE IF NOT EXISTS promotion_offer (
    id BIGINT NOT NULL,
    uuid TEXT NOT NULL,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    offer_no TEXT NOT NULL,
    offer_code TEXT,
    offer_type TEXT NOT NULL,
    audience_scope TEXT NOT NULL DEFAULT 'ALL',
    combinability TEXT NOT NULL DEFAULT 'EXCLUSIVE',
    priority INTEGER NOT NULL DEFAULT 0,
    goods_scope TEXT NOT NULL DEFAULT 'BOTH',
    current_offer_version_id BIGINT,
    display_name TEXT NOT NULL,
    description TEXT,
    starts_at TEXT NOT NULL,
    ends_at TEXT,
    status INTEGER NOT NULL DEFAULT 1,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT pk_promotion_offer PRIMARY KEY (id),
    CONSTRAINT uk_promotion_offer_uuid UNIQUE (uuid),
    CONSTRAINT uk_promotion_offer_no UNIQUE (tenant_id, offer_no),
    CONSTRAINT chk_promotion_offer_dates CHECK (ends_at IS NULL OR ends_at >= starts_at)
);

CREATE INDEX IF NOT EXISTS idx_promotion_offer_tenant_status
    ON promotion_offer (tenant_id, organization_id, status, priority DESC, starts_at DESC);
CREATE INDEX IF NOT EXISTS idx_promotion_offer_tenant_type
    ON promotion_offer (tenant_id, offer_type, status);

CREATE TABLE IF NOT EXISTS promotion_offer_version (
    id BIGINT NOT NULL,
    uuid TEXT NOT NULL,
    tenant_id BIGINT NOT NULL,
    offer_id BIGINT NOT NULL,
    version_no INTEGER NOT NULL,
    discount_type TEXT NOT NULL,
    discount_value TEXT NOT NULL DEFAULT '0',
    minimum_amount TEXT NOT NULL DEFAULT '0',
    maximum_discount_amount TEXT,
    maximum_quantity_per_order INTEGER NOT NULL DEFAULT 1,
    currency_code TEXT NOT NULL DEFAULT '',
    rule_json TEXT,
    stack_rule_json TEXT,
    created_at TEXT NOT NULL,
    CONSTRAINT pk_promotion_offer_version PRIMARY KEY (id),
    CONSTRAINT uk_promotion_offer_version_uuid UNIQUE (uuid),
    CONSTRAINT uk_promotion_offer_version_unique UNIQUE (tenant_id, offer_id, version_no),
    CONSTRAINT chk_promotion_offer_version_discount_non_negative CHECK (
        CAST(discount_value AS REAL) >= 0 AND CAST(minimum_amount AS REAL) >= 0
    )
);

CREATE INDEX IF NOT EXISTS idx_promotion_offer_version_offer
    ON promotion_offer_version (tenant_id, offer_id, version_no DESC);

CREATE TABLE IF NOT EXISTS promotion_coupon_stock (
    id BIGINT NOT NULL,
    uuid TEXT NOT NULL,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    offer_id BIGINT NOT NULL,
    offer_version_id BIGINT NOT NULL,
    stock_no TEXT NOT NULL,
    stock_type TEXT NOT NULL,
    total_quantity BIGINT NOT NULL DEFAULT 0,
    available_quantity BIGINT NOT NULL DEFAULT 0,
    claimed_quantity BIGINT NOT NULL DEFAULT 0,
    redeemed_quantity BIGINT NOT NULL DEFAULT 0,
    locked_quantity BIGINT NOT NULL DEFAULT 0,
    per_user_limit INTEGER NOT NULL DEFAULT 1,
    claim_starts_at TEXT,
    claim_ends_at TEXT,
    status INTEGER NOT NULL DEFAULT 1,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT pk_promotion_coupon_stock PRIMARY KEY (id),
    CONSTRAINT uk_promotion_coupon_stock_uuid UNIQUE (uuid),
    CONSTRAINT uk_promotion_coupon_stock_no UNIQUE (tenant_id, stock_no),
    CONSTRAINT chk_promotion_coupon_stock_quantities_non_negative CHECK (
        total_quantity >= 0 AND available_quantity >= 0 AND claimed_quantity >= 0
        AND redeemed_quantity >= 0 AND locked_quantity >= 0
    ),
    CONSTRAINT chk_promotion_coupon_stock_available_le_total CHECK (
        stock_type = 'UNLIMITED' OR (available_quantity + claimed_quantity <= total_quantity)
    )
);

CREATE INDEX IF NOT EXISTS idx_promotion_coupon_stock_offer
    ON promotion_coupon_stock (tenant_id, offer_id, status);

CREATE TABLE IF NOT EXISTS promotion_code (
    id BIGINT NOT NULL,
    uuid TEXT NOT NULL,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    stock_id BIGINT NOT NULL,
    offer_id BIGINT NOT NULL,
    offer_version_id BIGINT NOT NULL,
    code_no TEXT NOT NULL,
    promotion_code TEXT NOT NULL,
    code_type TEXT NOT NULL,
    max_claims INTEGER NOT NULL DEFAULT 1,
    claimed_quantity INTEGER NOT NULL DEFAULT 0,
    starts_at TEXT,
    expires_at TEXT,
    status INTEGER NOT NULL DEFAULT 1,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT pk_promotion_code PRIMARY KEY (id),
    CONSTRAINT uk_promotion_code_uuid UNIQUE (uuid),
    CONSTRAINT uk_promotion_code_no UNIQUE (tenant_id, code_no),
    CONSTRAINT uk_promotion_code_value UNIQUE (tenant_id, promotion_code),
    CONSTRAINT chk_promotion_code_claimed_le_max CHECK (claimed_quantity <= max_claims)
);

CREATE INDEX IF NOT EXISTS idx_promotion_code_stock
    ON promotion_code (tenant_id, stock_id, status);

CREATE TABLE IF NOT EXISTS promotion_user_coupon (
    id BIGINT NOT NULL,
    uuid TEXT NOT NULL,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    coupon_no TEXT NOT NULL,
    stock_id BIGINT NOT NULL,
    code_id BIGINT,
    offer_id BIGINT NOT NULL,
    offer_version_id BIGINT NOT NULL,
    subject_type TEXT NOT NULL,
    subject_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    coupon_code TEXT NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    claimed_at TEXT NOT NULL,
    valid_from TEXT NOT NULL,
    expires_at TEXT,
    redeemed_at TEXT,
    disabled_at TEXT,
    source_type TEXT,
    source_id BIGINT,
    request_no TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    trace_id TEXT NOT NULL DEFAULT '',
    version BIGINT NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT pk_promotion_user_coupon PRIMARY KEY (id),
    CONSTRAINT uk_promotion_user_coupon_uuid UNIQUE (uuid),
    CONSTRAINT uk_promotion_user_coupon_no UNIQUE (tenant_id, coupon_no),
    CONSTRAINT uk_promotion_user_coupon_idempotency UNIQUE (tenant_id, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_promotion_user_coupon_owner_status_expires
    ON promotion_user_coupon (tenant_id, owner_user_id, status, expires_at);
CREATE INDEX IF NOT EXISTS idx_promotion_user_coupon_offer
    ON promotion_user_coupon (tenant_id, offer_id, status);

CREATE TABLE IF NOT EXISTS promotion_coupon_ledger_entry (
    id BIGINT NOT NULL,
    uuid TEXT NOT NULL,
    tenant_id BIGINT NOT NULL,
    stock_id BIGINT NOT NULL,
    user_coupon_id BIGINT,
    offer_id BIGINT NOT NULL,
    subject_type TEXT,
    subject_id BIGINT,
    direction TEXT NOT NULL,
    quantity_delta BIGINT NOT NULL,
    balance_after BIGINT NOT NULL,
    business_type TEXT NOT NULL,
    business_no TEXT NOT NULL,
    request_no TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    source_type TEXT,
    source_id BIGINT,
    trace_id TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    CONSTRAINT pk_promotion_coupon_ledger_entry PRIMARY KEY (id),
    CONSTRAINT uk_promotion_coupon_ledger_entry_uuid UNIQUE (uuid),
    CONSTRAINT uk_promotion_coupon_ledger_entry_idempotency UNIQUE (tenant_id, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_promotion_coupon_ledger_entry_stock_created
    ON promotion_coupon_ledger_entry (tenant_id, stock_id, created_at DESC);

CREATE TABLE IF NOT EXISTS promotion_discount_application (
    id BIGINT NOT NULL,
    uuid TEXT NOT NULL,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    application_no TEXT NOT NULL,
    order_id BIGINT NOT NULL,
    order_no TEXT,
    user_coupon_id BIGINT,
    offer_id BIGINT NOT NULL,
    offer_version_id BIGINT NOT NULL,
    subject_type TEXT NOT NULL,
    subject_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    discount_type TEXT NOT NULL,
    discount_amount TEXT NOT NULL DEFAULT '0',
    currency_code TEXT NOT NULL DEFAULT '',
    discount_details_json TEXT,
    goods_type TEXT NOT NULL DEFAULT 'BOTH',
    status INTEGER NOT NULL DEFAULT 1,
    applied_at TEXT NOT NULL,
    settled_at TEXT,
    released_at TEXT,
    rolled_back_at TEXT,
    release_reason TEXT,
    rollback_reason TEXT,
    request_no TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    trace_id TEXT NOT NULL DEFAULT '',
    version BIGINT NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT pk_promotion_discount_application PRIMARY KEY (id),
    CONSTRAINT uk_promotion_discount_application_uuid UNIQUE (uuid),
    CONSTRAINT uk_promotion_discount_application_no UNIQUE (tenant_id, application_no),
    CONSTRAINT uk_promotion_discount_application_idempotency UNIQUE (tenant_id, idempotency_key),
    CONSTRAINT chk_promotion_discount_application_amount_non_negative CHECK (
        CAST(discount_amount AS REAL) >= 0
    )
);

CREATE INDEX IF NOT EXISTS idx_promotion_discount_application_owner_status
    ON promotion_discount_application (tenant_id, owner_user_id, status, applied_at DESC);
CREATE INDEX IF NOT EXISTS idx_promotion_discount_application_order
    ON promotion_discount_application (tenant_id, order_id, status);
