//! Generated gateway bootstrap for sdkwork-promotion.
//! Regenerated by pnpm gateway:assembly:materialize when bootstrap contains todo!().

use axum::Router;
use sdkwork_promotion_service_host::PromotionServiceHost;
use std::sync::Arc;

pub struct ApplicationAssembly {
    pub router: Router,
}

pub async fn assemble_application_router(host: Arc<PromotionServiceHost>) -> ApplicationAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_promotion_app_api::gateway_mount(host.clone()).await);
    router = router.merge(sdkwork_routes_promotion_backend_api::gateway_mount(host).await);
    ApplicationAssembly { router }
}
