-- SDKWork promotion consolidated initialization baseline (postgres)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/postgres/0001_promotion_baseline.sql
-- sdkwork:migration
-- id: 0001_promotion_core
-- engine: postgres
-- module: promotion
-- purpose: L2 promotion offer, coupon stock, code, user coupon, ledger, discount application
-- reversible: true
-- transactional: true

CREATE TABLE IF NOT EXISTS promotion_offer (
    id BIGINT NOT NULL,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    offer_no VARCHAR(128) NOT NULL,
    offer_code VARCHAR(128),
    offer_type VARCHAR(32) NOT NULL,
    audience_scope VARCHAR(32) NOT NULL DEFAULT 'ALL',
    combinability VARCHAR(32) NOT NULL DEFAULT 'EXCLUSIVE',
    priority INTEGER NOT NULL DEFAULT 0,
    goods_scope VARCHAR(32) NOT NULL DEFAULT 'BOTH',
    current_offer_version_id BIGINT,
    display_name VARCHAR(256) NOT NULL,
    description VARCHAR(1024),
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ,
    status INTEGER NOT NULL DEFAULT 1,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_promotion_offer PRIMARY KEY (id),
    CONSTRAINT uk_promotion_offer_uuid UNIQUE (uuid),
    CONSTRAINT uk_promotion_offer_no UNIQUE (tenant_id, offer_no),
    CONSTRAINT chk_promotion_offer_dates CHECK (ends_at IS NULL OR ends_at >= starts_at)
);

CREATE INDEX IF NOT EXISTS idx_promotion_offer_tenant_status
    ON promotion_offer (tenant_id, organization_id, status, priority DESC, starts_at DESC);
CREATE INDEX IF NOT EXISTS idx_promotion_offer_tenant_type
    ON promotion_offer (tenant_id, offer_type, status);

CREATE TABLE IF NOT EXISTS promotion_offer_version (
    id BIGINT NOT NULL,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    offer_id BIGINT NOT NULL,
    version_no INTEGER NOT NULL,
    discount_type VARCHAR(32) NOT NULL,
    discount_value NUMERIC(18, 2) NOT NULL DEFAULT 0,
    minimum_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    maximum_discount_amount NUMERIC(18, 2),
    maximum_quantity_per_order INTEGER NOT NULL DEFAULT 1,
    currency_code VARCHAR(10) NOT NULL DEFAULT '',
    rule_json JSONB,
    stack_rule_json JSONB,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_promotion_offer_version PRIMARY KEY (id),
    CONSTRAINT uk_promotion_offer_version_uuid UNIQUE (uuid),
    CONSTRAINT uk_promotion_offer_version_unique UNIQUE (tenant_id, offer_id, version_no),
    CONSTRAINT chk_promotion_offer_version_discount_non_negative CHECK (discount_value >= 0 AND minimum_amount >= 0)
);

CREATE INDEX IF NOT EXISTS idx_promotion_offer_version_offer
    ON promotion_offer_version (tenant_id, offer_id, version_no DESC);

CREATE TABLE IF NOT EXISTS promotion_coupon_stock (
    id BIGINT NOT NULL,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    offer_id BIGINT NOT NULL,
    offer_version_id BIGINT NOT NULL,
    stock_no VARCHAR(128) NOT NULL,
    stock_type VARCHAR(32) NOT NULL,
    total_quantity BIGINT NOT NULL DEFAULT 0,
    available_quantity BIGINT NOT NULL DEFAULT 0,
    claimed_quantity BIGINT NOT NULL DEFAULT 0,
    redeemed_quantity BIGINT NOT NULL DEFAULT 0,
    locked_quantity BIGINT NOT NULL DEFAULT 0,
    per_user_limit INTEGER NOT NULL DEFAULT 1,
    claim_starts_at TIMESTAMPTZ,
    claim_ends_at TIMESTAMPTZ,
    status INTEGER NOT NULL DEFAULT 1,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_promotion_coupon_stock PRIMARY KEY (id),
    CONSTRAINT uk_promotion_coupon_stock_uuid UNIQUE (uuid),
    CONSTRAINT uk_promotion_coupon_stock_no UNIQUE (tenant_id, stock_no),
    CONSTRAINT chk_promotion_coupon_stock_quantities_non_negative CHECK (
        total_quantity >= 0 AND available_quantity >= 0 AND claimed_quantity >= 0
        AND redeemed_quantity >= 0 AND locked_quantity >= 0
    ),
    CONSTRAINT chk_promotion_coupon_stock_available_le_total CHECK (
        stock_type = 'UNLIMITED' OR (available_quantity + claimed_quantity <= total_quantity)
    )
);

CREATE INDEX IF NOT EXISTS idx_promotion_coupon_stock_offer
    ON promotion_coupon_stock (tenant_id, offer_id, status);

CREATE TABLE IF NOT EXISTS promotion_code (
    id BIGINT NOT NULL,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    stock_id BIGINT NOT NULL,
    offer_id BIGINT NOT NULL,
    offer_version_id BIGINT NOT NULL,
    code_no VARCHAR(128) NOT NULL,
    promotion_code VARCHAR(128) NOT NULL,
    code_type VARCHAR(32) NOT NULL,
    max_claims INTEGER NOT NULL DEFAULT 1,
    claimed_quantity INTEGER NOT NULL DEFAULT 0,
    starts_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    status INTEGER NOT NULL DEFAULT 1,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_promotion_code PRIMARY KEY (id),
    CONSTRAINT uk_promotion_code_uuid UNIQUE (uuid),
    CONSTRAINT uk_promotion_code_no UNIQUE (tenant_id, code_no),
    CONSTRAINT uk_promotion_code_value UNIQUE (tenant_id, promotion_code),
    CONSTRAINT chk_promotion_code_claimed_le_max CHECK (claimed_quantity <= max_claims)
);

CREATE INDEX IF NOT EXISTS idx_promotion_code_stock
    ON promotion_code (tenant_id, stock_id, status);

CREATE TABLE IF NOT EXISTS promotion_user_coupon (
    id BIGINT NOT NULL,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    coupon_no VARCHAR(128) NOT NULL,
    stock_id BIGINT NOT NULL,
    code_id BIGINT,
    offer_id BIGINT NOT NULL,
    offer_version_id BIGINT NOT NULL,
    subject_type VARCHAR(32) NOT NULL,
    subject_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    coupon_code VARCHAR(128) NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    claimed_at TIMESTAMPTZ NOT NULL,
    valid_from TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ,
    redeemed_at TIMESTAMPTZ,
    disabled_at TIMESTAMPTZ,
    source_type VARCHAR(64),
    source_id BIGINT,
    request_no VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    trace_id VARCHAR(128) NOT NULL DEFAULT '',
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_promotion_user_coupon PRIMARY KEY (id),
    CONSTRAINT uk_promotion_user_coupon_uuid UNIQUE (uuid),
    CONSTRAINT uk_promotion_user_coupon_no UNIQUE (tenant_id, coupon_no),
    CONSTRAINT uk_promotion_user_coupon_idempotency UNIQUE (tenant_id, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_promotion_user_coupon_owner_status_expires
    ON promotion_user_coupon (tenant_id, owner_user_id, status, expires_at);
CREATE INDEX IF NOT EXISTS idx_promotion_user_coupon_offer
    ON promotion_user_coupon (tenant_id, offer_id, status);

CREATE TABLE IF NOT EXISTS promotion_coupon_ledger_entry (
    id BIGINT NOT NULL,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    stock_id BIGINT NOT NULL,
    user_coupon_id BIGINT,
    offer_id BIGINT NOT NULL,
    subject_type VARCHAR(32),
    subject_id BIGINT,
    direction VARCHAR(16) NOT NULL,
    quantity_delta BIGINT NOT NULL,
    balance_after BIGINT NOT NULL,
    business_type VARCHAR(64) NOT NULL,
    business_no VARCHAR(128) NOT NULL,
    request_no VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    source_type VARCHAR(64),
    source_id BIGINT,
    trace_id VARCHAR(128) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_promotion_coupon_ledger_entry PRIMARY KEY (id),
    CONSTRAINT uk_promotion_coupon_ledger_entry_uuid UNIQUE (uuid),
    CONSTRAINT uk_promotion_coupon_ledger_entry_idempotency UNIQUE (tenant_id, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_promotion_coupon_ledger_entry_stock_created
    ON promotion_coupon_ledger_entry (tenant_id, stock_id, created_at DESC);

CREATE TABLE IF NOT EXISTS promotion_discount_application (
    id BIGINT NOT NULL,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    application_no VARCHAR(128) NOT NULL,
    order_id BIGINT NOT NULL,
    order_no VARCHAR(128),
    user_coupon_id BIGINT,
    offer_id BIGINT NOT NULL,
    offer_version_id BIGINT NOT NULL,
    subject_type VARCHAR(32) NOT NULL,
    subject_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    discount_type VARCHAR(32) NOT NULL,
    discount_amount NUMERIC(18, 2) NOT NULL,
    currency_code VARCHAR(10) NOT NULL DEFAULT '',
    discount_details_json JSONB,
    goods_type VARCHAR(32) NOT NULL DEFAULT 'BOTH',
    status INTEGER NOT NULL DEFAULT 1,
    applied_at TIMESTAMPTZ NOT NULL,
    settled_at TIMESTAMPTZ,
    released_at TIMESTAMPTZ,
    rolled_back_at TIMESTAMPTZ,
    release_reason VARCHAR(512),
    rollback_reason VARCHAR(512),
    request_no VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    trace_id VARCHAR(128) NOT NULL DEFAULT '',
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_promotion_discount_application PRIMARY KEY (id),
    CONSTRAINT uk_promotion_discount_application_uuid UNIQUE (uuid),
    CONSTRAINT uk_promotion_discount_application_no UNIQUE (tenant_id, application_no),
    CONSTRAINT uk_promotion_discount_application_idempotency UNIQUE (tenant_id, idempotency_key),
    CONSTRAINT chk_promotion_discount_application_amount_non_negative CHECK (discount_amount >= 0)
);

CREATE INDEX IF NOT EXISTS idx_promotion_discount_application_owner_status
    ON promotion_discount_application (tenant_id, owner_user_id, status, applied_at DESC);
CREATE INDEX IF NOT EXISTS idx_promotion_discount_application_order
    ON promotion_discount_application (tenant_id, order_id, status);
